import type { Metadata } from "next";

import { Navbar } from "@/components/user";

//import { Toaster } from "@/components/ui";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	
	return (
		<>
			<Navbar />
			<main className="bg-[#FBFBFB] min-h-screen">{children}</main>
			{/* 		<Toaster /> */}
		</>
	);
}
