import { AppSidebar } from "@/components/admin/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Admin Dashboard",
	description: "Generated by create next app",
};

export default async function AdminLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<SidebarProvider>
			<AppSidebar />
			<main className="p-4 w-full">
				<SidebarTrigger />
				{children}
			</main>
		</SidebarProvider>
	);
}
